'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import type {MenuCategory} from '@/lib/types';
import {fullMenuItemName,modifierDisplay} from '@/lib/menu-names';

const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const supa=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||'http://127.0.0.1:54321',process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'development-anon-key');

export default function AdminApp(){
  const [client]=useState(supa),[session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[orders,setOrders]=useState<any[]>([]),[menu,setMenu]=useState<MenuCategory[]>([]),[settings,setSettings]=useState<any>(null),[tab,setTab]=useState('board'),[error,setError]=useState('');
  useEffect(()=>{client.auth.getSession().then(({data})=>setSession(data.session));const {data}=client.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[client]);
  async function api(url:string,opts:any={}){const r=await fetch(url,{...opts,headers:{'content-type':'application/json',authorization:`Bearer ${session?.access_token||''}`,...opts.headers},cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
  async function load(){if(!session)return;try{const [o,m,s]=await Promise.all([api('/api/admin/orders'),fetch('/api/menu',{cache:'no-store'}).then(r=>r.json()),fetch('/api/settings',{cache:'no-store'}).then(r=>r.json())]);setOrders(o);setMenu(m);setSettings(s);setError('')}catch(e:any){setError(e.message)}}
  useEffect(()=>{load();if(!session)return;const t=setInterval(load,8000);return()=>clearInterval(t)},[session]);
  async function login(e:any){e.preventDefault();setError('');const {error}=await client.auth.signInWithPassword({email,password});if(error)setError(error.message)}
  async function patchOrder(id:string,p:any){try{await api('/api/admin/orders',{method:'PATCH',body:JSON.stringify({id,...p})});load()}catch(e:any){setError(e.message)}}
  async function patchMenu(id:string,p:any){try{await api('/api/admin/menu',{method:'PATCH',body:JSON.stringify({id,...p})});load()}catch(e:any){setError(e.message)}}
  async function patchSettings(p:any){try{const s=await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify(p)});setSettings({...s,currentlyOpen:settings?.currentlyOpen})}catch(e:any){setError(e.message)}}

  if(!session)return <main className="admin-shell"><div className="admin-wrap" style={{maxWidth:500}}><h1>NO PROBLEMO · ADMIN</h1><p>Restaurant staff only.</p><form onSubmit={login}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><br/><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><br/><button className="chalk-btn" type="submit">SIGN IN</button><a className="admin-forgot-link" href="/admin/reset-password">FORGOT PASSWORD?</a>{error&&<p className="danger">{error}</p>}</form></div></main>;

  const active=orders.filter(o=>!o.archived&&!['cancelled','picked_up'].includes(o.fulfillment_status));
  const today=orders.filter(o=>new Date(o.created_at).toLocaleDateString('en-US',{timeZone:'America/New_York'})===new Date().toLocaleDateString('en-US',{timeZone:'America/New_York'}));
  const totals=today.reduce((a,o)=>({sales:a.sales+o.total_cents,paid:a.paid+(o.payment_status==='paid'?o.total_cents:0),unpaid:a.unpaid+(o.payment_status==='unpaid'?o.total_cents:0),count:a.count+1}),{sales:0,paid:0,unpaid:0,count:0});

  return <main className="admin-shell"><div className="admin-wrap"><div className="admin-top"><div><h1>NO PROBLEMO · KITCHEN BOARD</h1><p>{totals.count} today · {money(totals.sales)} ordered · {money(totals.paid)} paid · {money(totals.unpaid)} unpaid</p></div><button className="chalk-btn" onClick={()=>client.auth.signOut()}>SIGN OUT</button></div>{error&&<p className="danger">{error}</p>}<div className="admin-tabs" role="tablist" aria-label="Admin sections"><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}>ORDER BOARD <span>{active.length}</span></button><button className={tab==='manual'?'active primary':''} onClick={()=>setTab('manual')}>+ NEW ORDER</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>HISTORY</button><button className={tab==='menu'?'active':''} onClick={()=>setTab('menu')}>MENU</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>SETTINGS</button></div>
    {tab==='board'&&<div className="admin-columns"><OrderCol patch={patchOrder} title="NEW" orders={active.filter(o=>['new','accepted'].includes(o.fulfillment_status))} actions={(o:any)=><><button onClick={()=>patchOrder(o.id,{fulfillment_status:'accepted'})}>ACCEPT</button><button onClick={()=>patchOrder(o.id,{fulfillment_status:'cooking'})}>START COOKING</button><button className="danger" onClick={()=>patchOrder(o.id,{fulfillment_status:'cancelled'})}>CANCEL</button></>}/><OrderCol patch={patchOrder} title="COOKING" orders={active.filter(o=>o.fulfillment_status==='cooking')} actions={(o:any)=><button onClick={()=>patchOrder(o.id,{fulfillment_status:'ready'})}>MARK READY</button>}/><OrderCol patch={patchOrder} title="READY" orders={active.filter(o=>o.fulfillment_status==='ready')} actions={(o:any)=><><button onClick={()=>patchOrder(o.id,{fulfillment_status:'picked_up'})}>PICKED UP</button><button onClick={()=>patchOrder(o.id,{payment_status:o.payment_status==='paid'?'unpaid':'paid'})}>{o.payment_status==='paid'?'MARK UNPAID':'MARK PAID'}</button></>}/></div>}
    {tab==='manual'&&<ManualOrder menu={menu} create={async b=>{await api('/api/admin/orders',{method:'POST',body:JSON.stringify(b)});setTab('board');load()}}/>}
    {tab==='history'&&<History orders={orders} patch={patchOrder}/>} 
    {tab==='menu'&&<MenuManager menu={menu} save={patchMenu}/>} 
    {tab==='settings'&&settings&&<Settings settings={settings} setSettings={setSettings} save={patchSettings}/>} 
  </div></main>;
}

function OrderCol({title,orders,actions,patch}:{title:string;orders:any[];actions:(o:any)=>any;patch:(id:string,p:any)=>void}){
  return <section className="admin-col"><h2>{title} · {orders.length}</h2>{orders.map(o=><article className="admin-order" key={o.id}>
    <h3>#{String(o.order_number).padStart(3,'0')} · {o.customer_first_name}</h3>
    <div className="small">{new Date(o.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · {o.pickup_type==='asap'?'ASAP':o.pickup_time} · {String(o.source).toUpperCase()}</div>
    <div>{o.order_items?.map((i:any)=><div className="admin-line-item" key={i.id}><strong>{i.quantity} × {i.full_item_name||i.item_name_snapshot}</strong>{i.order_item_modifiers?.length>0&&<div className="admin-modifiers">{i.order_item_modifiers.map((m:any)=><span className={String(m.display||'').startsWith('REMOVE:')?'remove-mod':''} key={m.id}>{m.display||modifierDisplay(m.modifier_group_name,m.modifier_name_snapshot)}</span>)}</div>}{i.item_notes&&<div className="small"><strong>ITEM NOTE:</strong> {i.item_notes}</div>}</div>)}</div>
    {o.customer_notes&&<p><strong>ORDER NOTE:</strong> {o.customer_notes}</p>}
    <p><a style={{color:'inherit'}} href={`tel:${o.phone}`}>{o.phone}</a> · {money(o.total_cents)} · {o.payment_status.toUpperCase()}</p>
    <details><summary>FULL TICKET / NOTES</summary><p>Customer: {o.customer_first_name} {o.customer_last_name}<br/>Phone: {o.phone}<br/>Pickup: {o.pickup_type} {o.pickup_time||''}<br/>Fulfillment: {o.fulfillment_status}<br/>Payment: {o.payment_status}</p><p>Admin notes: {o.admin_notes||'—'}</p><div className="small">{o.order_status_history?.map((h:any)=><div key={h.id}>{new Date(h.created_at).toLocaleTimeString()} · {h.from_status||'start'} → {h.to_status} · {h.payment_status}</div>)}</div></details>
    <div className="admin-actions">{actions(o)}<button onClick={()=>{const v=window.prompt('Admin notes',o.admin_notes||'');if(v!==null)patch(o.id,{admin_notes:v})}}>EDIT NOTES</button><button onClick={()=>{const v=window.prompt('Pickup time',o.pickup_time||'');if(v!==null)patch(o.id,{pickup_time:v})}}>EDIT PICKUP</button></div>
  </article>)}</section>;
}

function History({orders,patch}:{orders:any[];patch:(id:string,p:any)=>void}){const [q,setQ]=useState('');const rows=orders.filter(o=>`${o.order_number} ${o.customer_first_name} ${o.customer_last_name} ${o.phone}`.toLowerCase().includes(q.toLowerCase()));return <><input placeholder="Search order #, customer or phone" value={q} onChange={e=>setQ(e.target.value)}/><div className="table-wrap"><table className="admin-table"><thead><tr><th>#</th><th>Time</th><th>Customer</th><th>Items</th><th>Phone</th><th>Source</th><th>Status</th><th>Payment</th><th>Total</th><th>Archive</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td>#{String(o.order_number).padStart(3,'0')}</td><td>{new Date(o.created_at).toLocaleString()}</td><td>{o.customer_first_name} {o.customer_last_name}</td><td>{o.order_items?.map((i:any)=><div key={i.id}>{i.quantity} × {i.full_item_name||i.item_name_snapshot}</div>)}</td><td>{o.phone}</td><td>{o.source}</td><td>{o.fulfillment_status}</td><td>{o.payment_status}</td><td>{money(o.total_cents)}</td><td><button onClick={()=>patch(o.id,{archived:!o.archived})}>{o.archived?'UNARCHIVE':'ARCHIVE'}</button></td></tr>)}</tbody></table></div></>}

function MenuManager({menu,save}:{menu:MenuCategory[];save:(id:string,p:any)=>void}){const groups=useMemo(()=>{const m=new Map<string,any>();menu.forEach(c=>c.items.forEach(i=>i.modifier_groups.forEach(g=>m.set(g.id,g))));return [...m.values()]},[menu]);return <div>{menu.map(c=><section key={c.id}><div className="admin-top"><h2>{c.name}</h2><button onClick={()=>save(c.id,{kind:'category',sort_order:c.sort_order-1})}>MOVE UP</button></div><div className="table-wrap"><table className="admin-table"><thead><tr><th>Item</th><th>Description</th><th>Price</th><th>Order</th><th>Active</th><th>Sold Out</th><th>Save</th></tr></thead><tbody>{c.items.map(i=><MenuRow key={i.id} item={i} category={c.name} save={save}/>)}</tbody></table></div></section>)}<h2>MODIFIER PRICES & AVAILABILITY</h2>{groups.map(g=><section key={g.id}><h3>{g.name}</h3><div className="table-wrap"><table className="admin-table"><tbody>{g.options.map((o:any)=><ModifierRow key={o.id} option={o} save={save}/>)}</tbody></table></div></section>)}</div>}
function MenuRow({item,category,save}:{item:any;category:string;save:(id:string,p:any)=>void}){const [name,setName]=useState(item.name),[desc,setDesc]=useState(item.description),[price,setPrice]=useState((item.price_cents/100).toFixed(2)),[sort,setSort]=useState(item.sort_order),[active,setActive]=useState(item.active),[sold,setSold]=useState(item.sold_out);return <tr><td><div className="small">Displays as: {fullMenuItemName(name,category)}</div><input value={name} onChange={e=>setName(e.target.value)}/></td><td><textarea rows={2} value={desc} onChange={e=>setDesc(e.target.value)}/></td><td><input value={price} onChange={e=>setPrice(e.target.value)} inputMode="decimal"/></td><td><input type="number" value={sort} onChange={e=>setSort(Number(e.target.value))}/></td><td><input style={{width:22}} type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/></td><td><input style={{width:22}} type="checkbox" checked={sold} onChange={e=>setSold(e.target.checked)}/></td><td><button onClick={()=>save(item.id,{name,description:desc,price_cents:Math.round(Number(price)*100),sort_order:sort,active,sold_out:sold})}>SAVE</button></td></tr>}
function ModifierRow({option,save}:{option:any;save:(id:string,p:any)=>void}){const [name,setName]=useState(option.name),[price,setPrice]=useState((option.price_cents/100).toFixed(2)),[active,setActive]=useState(option.active);return <tr><td><input value={name} onChange={e=>setName(e.target.value)}/></td><td><input value={price} onChange={e=>setPrice(e.target.value)}/></td><td><label><input style={{width:22}} type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> active</label></td><td><button onClick={()=>save(option.id,{kind:'modifier',name,price_cents:Math.round(Number(price)*100),active})}>SAVE</button></td></tr>}
function ManualOrder({menu,create}:{menu:MenuCategory[];create:(b:any)=>Promise<void>}){
  const [category,setCategory]=useState(menu[0]?.id||''),[search,setSearch]=useState(''),[cart,setCart]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[firstName,setFirst]=useState(''),[lastName,setLast]=useState(''),[phone,setPhone]=useState(''),[source,setSource]=useState('walk_in'),[notes,setNotes]=useState(''),[pickupType,setPickupType]=useState('asap'),[pickupTime,setPickupTime]=useState(''),[submitting,setSubmitting]=useState(false),[localError,setLocalError]=useState('');
  useEffect(()=>{if(!category&&menu[0])setCategory(menu[0].id)},[menu,category]);
  const current=menu.find(c=>c.id===category)||menu[0];
  const visible=(current?.items||[]).filter(i=>i.active&&!i.sold_out&&`${i.name} ${i.description}`.toLowerCase().includes(search.toLowerCase()));
  const lineTotal=(line:any)=>(line.item.price_cents+line.choices.reduce((a:number,c:any)=>a+c.price_cents,0))*line.quantity;
  const total=cart.reduce((a,l)=>a+lineTotal(l),0);
  const count=cart.reduce((a,l)=>a+l.quantity,0);
  function addLine(item:any,choices:any[],quantity:number,itemNotes:string){setCart(prev=>editing?.lineKey?prev.map(l=>l.key===editing.lineKey?{...l,item,choices,quantity,itemNotes}:l):[...prev,{key:`${item.id}-${Date.now()}-${Math.random()}`,item,choices,quantity,itemNotes}]);setEditing(null)}
  function updateQty(key:string,delta:number){setCart(prev=>prev.map(l=>l.key===key?{...l,quantity:Math.max(1,Math.min(50,l.quantity+delta))}:l))}
  function removeLine(key:string){setCart(prev=>prev.filter(l=>l.key!==key))}
  async function submit(){
    if(!firstName.trim()||!cart.length)return;
    setSubmitting(true);setLocalError('');
    try{await create({firstName:firstName.trim(),lastName:lastName.trim(),phone:phone.trim(),source,notes:notes.trim(),pickupType,pickupTime:pickupType==='scheduled'?pickupTime:null,items:cart.map(l=>({menu_item_id:l.item.id,quantity:l.quantity,item_notes:l.itemNotes,modifier_option_ids:l.choices.map((c:any)=>c.optionId)}))})}
    catch(e:any){setLocalError(e.message||'Could not create order');setSubmitting(false)}
  }
  return <div className="manual-order-shell">
    <div className="manual-order-head"><div><span className="eyebrow">CASHIER ORDER ENTRY</span><h2>NEW ORDER</h2><p>Build the ticket the same way a customer would, with every modifier and note attached to the correct item.</p></div><div className="manual-running-total"><span>{count} ITEM{count===1?'':'S'}</span><strong>{money(total)}</strong></div></div>
    <div className="manual-order-grid">
      <aside className="manual-categories"><div className="manual-search"><input aria-label="Search menu" placeholder="Search menu…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{menu.map(c=><button key={c.id} className={c.id===current?.id?'active':''} onClick={()=>{setCategory(c.id);setSearch('')}}><span>{c.name}</span><small>{c.items.filter(i=>i.active&&!i.sold_out).length}</small></button>)}</aside>
      <section className="manual-menu"><div className="manual-section-title"><div><span className="eyebrow">MENU</span><h3>{current?.name||'Menu'}</h3></div><span>{visible.length} available</span></div><div className="manual-item-grid">{visible.map(i=><button className="manual-item-card" key={i.id} onClick={()=>setEditing({item:i,displayName:fullMenuItemName(i.name,current?.name)})}><div><strong>{fullMenuItemName(i.name,current?.name)}</strong><p>{i.description}</p></div><span>{money(i.price_cents)}</span><b>ADD +</b></button>)}</div>{!visible.length&&<div className="admin-empty">No available items match this search.</div>}</section>
      <aside className="manual-ticket"><div className="manual-section-title"><div><span className="eyebrow">CURRENT TICKET</span><h3>ORDER</h3></div><span>{count} items</span></div>{!cart.length?<div className="admin-empty">Tap a menu item to start the order.</div>:<div className="manual-cart-lines">{cart.map(l=><div className="manual-cart-line" key={l.key}><div className="manual-cart-main"><strong>{l.quantity} × {fullMenuItemName(l.item.name,menu.find(c=>c.id===l.item.category_id)?.name)}</strong><b>{money(lineTotal(l))}</b></div>{l.choices.map((c:any)=><span key={c.optionId}>{modifierDisplay(c.groupName,c.optionName)}{c.price_cents>0?` +${money(c.price_cents)}`:''}</span>)}{l.itemNotes&&<span>NOTE: {l.itemNotes}</span>}<div className="manual-line-actions"><button onClick={()=>updateQty(l.key,-1)}>−</button><em>{l.quantity}</em><button onClick={()=>updateQty(l.key,1)}>+</button><button className="edit-link" onClick={()=>setEditing({item:l.item,displayName:fullMenuItemName(l.item.name,menu.find(c=>c.id===l.item.category_id)?.name),lineKey:l.key,line:l})}>EDIT</button><button className="danger-link" onClick={()=>removeLine(l.key)}>REMOVE</button></div></div>)}</div>}
        <div className="manual-total"><span>TOTAL</span><strong>{money(total)}</strong></div>
        <div className="manual-customer"><h4>CUSTOMER & PICKUP</h4><div className="admin-form compact"><label>First name *<input autoComplete="off" value={firstName} onChange={e=>setFirst(e.target.value)} placeholder="Customer name"/></label><label>Last name<input autoComplete="off" value={lastName} onChange={e=>setLast(e.target.value)}/></label><label>Phone<input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Optional for walk-in"/></label><label>Order source<select value={source} onChange={e=>setSource(e.target.value)}><option value="walk_in">Walk-in</option><option value="phone">Phone</option><option value="admin">Admin</option></select></label><label>Pickup<select value={pickupType} onChange={e=>setPickupType(e.target.value)}><option value="asap">ASAP</option><option value="scheduled">Scheduled</option></select></label>{pickupType==='scheduled'&&<label>Pickup time<input value={pickupTime} onChange={e=>setPickupTime(e.target.value)} placeholder="e.g. 6:30 PM"/></label>}<label className="wide">Order note<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Whole-order note for kitchen/cashier"/></label></div></div>
        {localError&&<p className="danger">{localError}</p>}<button className="chalk-btn accent manual-submit" disabled={!firstName.trim()||!cart.length||submitting} onClick={submit}>{submitting?'CREATING ORDER…':`CREATE ORDER · ${money(total)}`}</button>
      </aside>
    </div>
    {editing&&<ManualItemModal item={editing.item} displayName={editing.displayName} initialLine={editing.line} onClose={()=>setEditing(null)} onAdd={addLine}/>} 
  </div>
}

function ManualItemModal({item,displayName,initialLine,onClose,onAdd}:{item:any;displayName:string;initialLine?:any;onClose:()=>void;onAdd:(i:any,c:any[],q:number,n:string)=>void}){
  const initialSelected:Record<string,string[]>={};for(const c of initialLine?.choices||[])(initialSelected[c.groupId]||=[]).push(c.optionId);
  const [selected,setSelected]=useState<Record<string,string[]>>(initialSelected),[q,setQ]=useState(initialLine?.quantity||1),[notes,setNotes]=useState(initialLine?.itemNotes||'');
  useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc)},[onClose]);
  function toggle(g:any,id:string){setSelected(prev=>{const cur=prev[g.id]||[];if(g.selection_type==='single')return {...prev,[g.id]:cur.includes(id)?[]:[id]};const has=cur.includes(id);if(has)return {...prev,[g.id]:cur.filter(x=>x!==id)};if(g.max_select&&cur.length>=g.max_select)return prev;return {...prev,[g.id]:[...cur,id]}})}
  const choices=item.modifier_groups.flatMap((g:any)=>(selected[g.id]||[]).map((id:string)=>{const o=g.options.find((x:any)=>x.id===id);return {groupId:g.id,groupName:g.name,optionId:o.id,optionName:o.name,price_cents:o.price_cents}}));
  const valid=item.modifier_groups.every((g:any)=>!g.required||(selected[g.id]||[]).length>=Math.max(1,g.min_select||1));
  const unit=item.price_cents+choices.reduce((a:number,c:any)=>a+c.price_cents,0),total=unit*q;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal manual-item-modal" role="dialog" aria-modal="true"><button type="button" className="close" aria-label="Close item details" onPointerDown={e=>{e.preventDefault();e.stopPropagation();onClose()}}>×</button><span className="eyebrow">CUSTOMIZE ITEM</span><h2>{displayName}</h2><p>{item.description}</p><strong>{money(item.price_cents)}</strong>{item.modifier_groups.map((g:any)=><div className="modifier" key={g.id}><h4>{g.name}{g.required?' *':''}</h4>{g.options.filter((o:any)=>o.active).map((o:any)=><label className="choice" key={o.id}><input type={g.selection_type==='single'?'radio':'checkbox'} name={`admin-${g.id}`} checked={(selected[g.id]||[]).includes(o.id)} onChange={()=>toggle(g,o.id)}/><span>{o.name}{o.price_cents?` (+${money(o.price_cents)})`:''}</span></label>)}</div>)}<div className="modifier"><label>Item note</label><textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={300} rows={2} placeholder="Special instruction for this item"/></div><div className="qty"><button onClick={()=>setQ(Math.max(1,q-1))}>−</button><strong>{q}</strong><button onClick={()=>setQ(Math.min(50,q+1))}>+</button></div><button className="chalk-btn accent manual-modal-add" disabled={!valid} onClick={()=>onAdd(item,choices,q,notes)}>{valid?`${initialLine?'SAVE ITEM':'ADD TO ORDER'} · ${money(total)}`:'SELECT REQUIRED OPTIONS'}</button></div></div>
}

function Settings({settings,setSettings,save}:{settings:any;setSettings:(s:any)=>void;save:(p:any)=>void}){const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];const updateHours=(day:string,n:number,v:string)=>{const hours={...settings.hours,[day]:settings.hours[day].map((x:string,i:number)=>i===n?v:x)};setSettings({...settings,hours});save({hours})};return <div className="chalk-panel"><h2>RESTAURANT SETTINGS</h2><div className="admin-form"><label>Online ordering<select value={String(settings.onlineOrderingEnabled)} onChange={e=>save({onlineOrderingEnabled:e.target.value==='true'})}><option value="true">OPEN</option><option value="false">PAUSED</option></select></label><label>Open override<select value={settings.restaurantOpenOverride||'normal'} onChange={e=>save({restaurantOpenOverride:e.target.value})}><option value="normal">NORMAL HOURS</option><option value="open">FORCE OPEN</option><option value="closed">FORCE CLOSED</option></select></label><label>Wait minutes<select value={settings.currentWaitMinutes} onChange={e=>save({currentWaitMinutes:Number(e.target.value)})}>{[10,20,30,45,60].map(x=><option key={x}>{x}</option>)}</select></label><label>Phone<input value={settings.phone||''} onChange={e=>setSettings({...settings,phone:e.target.value})} onBlur={()=>save({phone:settings.phone})}/></label><label style={{gridColumn:'span 2'}}>Address<input value={settings.address||''} onChange={e=>setSettings({...settings,address:e.target.value})} onBlur={()=>save({address:settings.address})}/></label><label style={{gridColumn:'1/-1'}}>Announcement<textarea value={settings.announcement||''} onChange={e=>setSettings({...settings,announcement:e.target.value})} onBlur={()=>save({announcement:settings.announcement})}/></label></div><h3>HOURS · AMERICA/NEW_YORK</h3><div className="admin-form">{days.map(d=><div key={d}><strong>{d.toUpperCase()}</strong><div style={{display:'flex',gap:6}}><input type="time" value={settings.hours[d][0]} onChange={e=>updateHours(d,0,e.target.value)}/><input type="time" value={settings.hours[d][1]} onChange={e=>updateHours(d,1,e.target.value)}/></div></div>)}</div></div>}
